// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/2fc3a43ab80b98afaabcc676e9de92517b3c2d35/highcharts/highcharts-modules-exporting.d.ts
declare var HighchartsExporting: (H: HighchartsStatic) => HighchartsStatic;

declare module "highcharts/modules/exporting" {
    export = HighchartsExporting;
}